# Generated by Django 3.2.5 on 2023-04-10 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resin',
            fields=[
                ('material_type', models.CharField(max_length=10)),
                ('resin_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('model', models.CharField(max_length=10)),
                ('product_code', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('machine_tonnage', models.IntegerField()),
                ('cavity', models.CharField(max_length=10)),
                ('ct', models.CharField(max_length=20)),
                ('week_produce', models.CharField(max_length=10)),
                ('night_produce', models.CharField(max_length=10)),
                ('real_weight', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.client')),
                ('resin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.resin')),
            ],
        ),
    ]
