# Generated by Django 3.2.5 on 2023-04-18 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20230418_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resin',
            name='client_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.client'),
        ),
        migrations.AlterField(
            model_name='resin',
            name='material_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
