# Generated by Django 3.2.5 on 2023-04-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20230424_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vol',
        ),
    ]
