# Generated by Django 3.2.5 on 2023-04-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_order_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distributed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='produced',
            field=models.IntegerField(default=0),
        ),
    ]
