# Generated by Django 3.2.5 on 2023-04-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20230427_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='machine_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
